public class Room {
	/* Potential methods: 
		Constructor (could probably get away with default)

		ADD ROOM ADJECTIVE
		ADD FURNITURE WITH ADJECTIVE
		ADD DOOR NORTH WITH ADJECTIVE
		ADD DOOR SOUTH WITH ADJECTIVE

		GET ROOM DESCRIPTION
		GET FURNITURE DESCRIPTION
		GET NORTH DESCRIPTION
		GET SOUTH DESCRIPTION
	*/	
}
